mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^home/$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^logout_view/$', views.logout_view, name='logout_view'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^operationalDashboard/$', views.login_operational_user, name='login_operational_user'),
    url(r'^register/$', views.register , name='register'),
    url(r'^search/$', views.searchResults, name='searchResults'),
]

blog/models.py
from django.db import models

class Table1(models.Model):
    locker_id = models.IntegerField(primary_key=True)
    locker_name = models.CharField(db_column='Locker_name', max_length=45, blank=True, null=True)  # Field name made lowercase.
    city = models.CharField(max_length=45, blank=True, null=True)
    state = models.CharField(max_length=45, blank=True, null=True)
    pincode = models.CharField(max_length=45, blank=True, null=True)
    prime_capacity = models.CharField(max_length=45, blank=True, null=True)
    standard_capacity = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        #db_table = 'table1'
        


class Prime(models.Model):
    key_p = models.AutoField(primary_key=True)
    locker = models.ForeignKey(Table1)
    day0 = models.IntegerField(blank=True, null=True)
    day1 = models.IntegerField(blank=True, null=True)
    day2 = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        #db_table = 'prime'


class Standard(models.Model):
    key_s = models.AutoField(primary_key=True)
    locker = models.ForeignKey(Table1)
    day0 = models.IntegerField(blank=True, null=True)
    day1 = models.IntegerField(blank=True, null=True)
    day2 = models.IntegerField(blank=True, null=True)
    day3 = models.IntegerField(blank=True, null=True)
    day4 = models.IntegerField(blank=True, null=True)
    day5 = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
       # db_table = 'standard'

blog/forms.py
from django import forms #django already has a class called forms

from .models import Table1
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    Prime_percentage=forms.CharField()
    class Meta:
        model = Table1 #will follow the Post Model
        fields = ('locker_id','locker_name','city','state','pincode','prime_capacity','standard_capacity','Prime_percentage')



class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username','email','password']

blog/views.py
from django.shortcuts import render
from .models import Table1,Prime,Standard
from django.shortcuts import render, get_object_or_404

from django.shortcuts import redirect
from django.db.models import Q
#from django.core.context_processors import csrf
from django.conf import settings
from django import http
from .forms import UserForm, PostForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponse



def post_edit(request, pk):
    post = get_object_or_404(Table1, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():            
            post = form.save(commit=False)
            post.save()
            return redirect('post_detail', pk=pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})



"""

def post_edit(request, pk):
    post = get_object_or_404(Table1, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            CapacityPrime = request.POST.get('prime_capacity')
            #CapacityPrime = int(CapacityPrime)
            CapacityStd = request.POST.get('standard_capacity')
            #CapacityStd = int(CapacityStd)
            ob = Prime.objects.get(locker=pk)
            occupiedPrime = ob.day2
            ob2 = Standard.objects.get(locker=pk)
            occupiedStd = ob2.day5
            if CapacityPrime >= occupiedPrime and  CapacityStd >=occupiedStd :
                post = form.save(commit=False)
                post.save()
                return redirect('post_detail', pk=pk)
        else :
            return HttpResponse("ERROR : Capacity allotted is less than occupied slots.")
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

"""





def post_remove(request, pk):
    post = get_object_or_404(Table1, pk=pk)
    posts = Table1.objects.all()
    post.delete()
    return render('blog/post_list.html',{'posts' : posts})


"""
def post_remove(request, pk):
    post = get_object_or_404(Table1, pk=pk)
    ob = Prime.objects.get(locker=pk)
    occupiedPrime = ob.day2
    ob2 = Standard.objects.get(locker=pk)
    occupiedStd = ob2.day5
    if occupiedStd >0 or occupiedPrime >0 :
        return HttpResponse("ERROR :Can't delete this locker as already occupied")
    else :
        post.delete()
    return redirect('blog.views.post_list')
   """ 


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)    #method name -GET or Post is specified in the dictionary value
        if form.is_valid():
            post = form.save(commit=False)
            #post.locker_name = request.user -request.user means the requesting user
            post.save()
            return redirect('post_detail', pk=post.pk)
            #return render(request,'blog/post_edit.html',{'form':form})
    else:
        form = PostForm()
    return render(request, 'blog/post_add.html', {'form': form})




#from django.shortcuts import render_to_response
def searchResults(request):
    posts = Table1.objects.all()
    query=request.GET.get("q")
    if query:
        posts = posts.filter(
            Q(city__iexact=query)|
            Q(state__iexact=query)|
            Q(locker_name__icontains=query)|
            Q(pincode__iexact=query)|
            Q(standard_capacity__iexact=query)|
            Q(prime_capacity__iexact=query)|
            Q(locker_id__iexact=query)
            ).distinct()
    return render(request, 'blog/post_list.html', {'posts': posts})


#queryset_list=queryset_list.filter, cant use queryset as queryset is empty
def post_list(request):
    posts = Table1.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, pk):  #matches url of type post/2005
    post = get_object_or_404(Table1, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})





def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                posts = Table1.objects.all()
                return render(request, 'blog/post_list.html', {'posts': posts})
            else:
                return render(request, 'blog/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'blog/login.html', {'error_message': 'Invalid login'})
    return render(request, 'blog/login.html')


from django.http import HttpResponse
def login_operational_user(request):
    if request.method == "POST":
        mail = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=mail, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponse("Operational Dashboard")
                #posts = Table1.objects.all()
                #return render(request, 'blog/post_list.html', {'posts': posts})
                
            else:
                return render(request, 'blog/loginoperational.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'blog/loginoperational.html', {'error_message': 'Invalid login'})
    return render(request, 'blog/loginoperational.html')



from django.http import HttpResponse
def logout_view(request):
    logout(request)
    return HttpResponse("You have been successfuly logged out")


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password, email=email)
        if user is not None: 
            if user.is_active:
                #login(request, user)
                q=1
                return render(request,'blog/post_list.html', {'q': q})
        return render(request,'blog/post_list.html', {'q': q})


    context ={
        "form": form,
    }
    return render(request, 'blog/registration_form.html', context)
#

blog/templates/blog/base.html
{%load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" >


<title>{%block title%}Onboarding Dashboard{%endblock%}</title>

<!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">-->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>



<body>

<nav class="navbar navbar-"  id="myScrollspy">
<div class="container-fluid">
<div class="navbar-header">

<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">

<span class="icon-bar"></span> 
<span class="icon-bar"></span>
<span class="icon-bar"></span>

</button>                            
</div>



{%if user.is_authenticated%}
<form class="navbar-form navbar-left" role="search" method="GET" action="{% url 'searchResults' %}">
<div class="form-group">
<input type="text" class="form-control" name="q" placeholder="Search for Lockers" value="{{request.GET.q}}"/>  </div>

<button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search" >&nbsp;Search</span></button>
</form>
{%endif%}

{%if q%}
<p style = "font-family: Arial; color: Red; size:70px">You have been successfully registered. Please login to continue. </p>

{%endif%}



{%if user.is_authenticated%}
<li class="nav navbar-nav navbar-right"   >

<a href = "{% url 'post_new'%}">
<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
Add locker
</a>
</li>
{%endif%}




{%comment%}
{%if not user.is_authenticated %}
    <li class="nav navbar-nav " >
       <a href = "{% url 'item' %}">
       <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
       <font face="ArialBlack" color = "" size="50"></font>User&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   </a>
   </li>
   {%endif%}

{%endcomment%}


{%if not user.is_authenticated%}
<li  class="nav navbar-nav navbar-right">
<a href = "{% url 'register' %}">
<span class="glyphicon glyphicon-check" aria-hidden="true"></span>&nbsp;
<font face="ArialBlack" color = "" size="50"></font>Register
</a>
</li>
{%endif%}







{%if not user.is_authenticated%}
<li class="nav navbar-nav navbar-right" >
<a href = "{% url 'login_user' %}">
<span class="glyphicon glyphicon-check" aria-hidden="true"></span>
<font face="ArialBlack" color = "" size="50"></font>Login-Onboarding Dashboard&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</a>
</li>
{%endif%}

{%if not user.is_authenticated%}
<li class="nav navbar-nav navbar-right" >
<a href = "{% url 'login_operational_user' %}">
<span class="glyphicon glyphicon-check" aria-hidden="true"></span>
<font face="ArialBlack" color = "" size="50"></font>Login-Operational Dashboard&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</a>
</li>
{%endif%}


{%if not user.is_authenticated%}
<img src="http://www.jazva.com/cm/Amazon-logo-700x433.jpg"  align="middle">

{%endif%}

{%if user.is_authenticated%}
<li  class="nav navbar-nav navbar-right">
<a href = "{% url 'logout_view' %}">
<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
Logout&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</a>
</li>
{%endif%}
{% if user.is_authenticated %}
<a href = "{% url 'post_list' %}">
<button class="btn btn-default"><span class="glyphicon glyphicon-home" aria-hidden="true">Home</span></button>
</a>
{%endif%}



{% block login %}
{%endblock%}


{% block part %}
{%endblock%}

{% block content %}
{%endblock%}


{% block edit %}
{%endblock%}


{%comment AA%}
<a href = "{% url 'users_view'%}">
<span class="glyphicon glyphicon" aria-hidden="true"></span>&nbsp;
UsersView
</a>
{%endcomment%}


</div>
</div>
</nav>



{% block postdetail %}
{% endblock %}


{% if user.is_authenticated %}
{%block postlist%}  
{%endblock%}
{%endif%}

blog/templates/blog/form-template.html
{%for field in form%}
    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-3">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>

        <div class="col-sm-2">{{field}}</div><!__actual input area__>
    </div>
{%endfor%}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block title %}Log In{% endblock %}


{% block login %}
<div class="container-fluid">

<div class="row">
<div class="col-sm-12 col-md-6">
<div class="panel panel-default">
<div class="panel-body">
<h3>Log In</h3>
{%comment aa%}  {%endcomment%}
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}


<form class="form-horizontal" role="form" action="{% url 'login_user'%}" method="post" enctype="multipart/form-data">

{% csrf_token %}
<div class="form-group">
<label class="control-label col-sm-2" for="id_username">
Username:
</label>
<div class="col-sm-10">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="id_username" maxlength="30" name="username" type="text">
</div>
</div>
<div class="form-group">
<label class="control-label col-sm-2" for="id_password">Password:
</label>
<div class="col-sm-10">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input id="id_password" maxlength="30" name="password" type="password">
</div>
</div>
<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<button type="submit" class="btn btn-danger" align="center">Submit</button>
</div>
</div>
</form>

<div class="panel-footer">
<br>Don't have an account? <a href="{% url 'register' %}">Click here</a> to register.
</div>
</div>
</div>
</div>
</div>

</div>

{% endblock %}

blog/templates/blog/loginoperational.html
{% extends 'blog/base.html' %}
{% block title %}Log In{% endblock %}


{% block login %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                     {%comment aa%}  {%endcomment%}
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}


                    <form class="form-horizontal" role="form" action="{% url 'login_operational_user'%}" method="post" enctype="multipart/form-data">

                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Email/Username :
                            </label>
                            <div class="col-sm-10">
                                 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                <div class="panel-footer">
                    <br>Don't have an account? <a href="{% url 'register' %}">Click here</a> to register.
                </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

blog/templates/blog/post_add.html
{% extends 'blog/base.html' %}
{%block title%} Add new {%endblock%}


{% block content %}
    <h3 class="newpost">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Add a new locker</h3>
		<form method="post" class="form-horizontal" action="" enctype="multipart/form-data">{% csrf_token %}


    {%include 'blog/form-template.html'%}
        <div class="form-group">
            <div class="col-sm-offset-2-col-sm-3">
        
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type="submit" class="btn btn-success">Submit</button>
                </div>
        </div>
    </form>
{% endblock %}

<!csrf token is for security purpose>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block postdetail %}

    <p>


        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil">Update</span></a>
        <p>Locker Id: {{ post.locker_id }}</p>
    <p>Locker Name: {{ post.locker_name }}</p>
    <p>Locker City: {{ post.city }}</p>
    <p>Locker State: {{ post.state }}</p>
    <p>Locker Pincode: {{ post.pincode }}</p>
    <p>Prime Capacity: {{ post.prime_capacity}}</p>
    <p>Standard Capacity: {{ post.standard_capacity }}</p>
       

{%endblock%}

blog/templates/blog/post_edit.html
{% extends 'blog\base.html' %}
{%block title%} Edit Locker {%endblock%}
{% block edit %}
    <h3 class="newpost">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Edit the locker</h3>
    <script type="text/javascript">
    	function errorAlert(){
    		var x = document.getElementById("a").value;
    		if(x==0)
    			alert("Please enter a higher prime percentage");
    	}
    	window.onload=errorAlert;
    	function putValue(){
    		var x = document.getElementById("id_Prime_percentage").value;
    		document.getElementById("std").value=100-x;
    	}
    </script>
	<form method="post" class="form-horizontal" action="" enctype="multipart/form-data">{% csrf_token %}
		<input type="text" value="{{ a }}" id="a" hidden/>
	    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-3">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2"><label for="id_locker_id">Locker id:</label></label>

        <div class="col-sm-2"><input id="id_locker_id" name="locker_id" type="number" value="{{form.locker_id.value}}" required /></div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-3">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2"><label for="id_locker_name">Locker name:</label></label>

        <div class="col-sm-2"><input id="id_locker_name" maxlength="45" name="locker_name" type="text" value="{{form.locker_name.value}}" /></div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-3">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2"><label for="id_city">City:</label></label>

        <div class="col-sm-2"><input id="id_city" maxlength="45" name="city" type="text" value="{{form.city.value}}" /></div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-3">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2"><label for="id_state">State:</label></label>

        <div class="col-sm-2"><input id="id_state" maxlength="45" name="state" type="text" value="{{form.state.value}}" /></div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-3">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2"><label for="id_pincode">Pincode:</label></label>

        <div class="col-sm-2"><input id="id_pincode" maxlength="45" name="pincode" type="text" value="{{form.pincode.value}}" /></div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-3">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2"><label for="id_prime_capacity">Prime capacity:</label></label>

        <div class="col-sm-2"><input id="id_prime_capacity" maxlength="45" name="prime_capacity" type="text" value="{{form.prime_capacity.value}}" disabled /></div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-3">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2"><label for="id_standard_capacity">Standard capacity:</label></label>

        <div class="col-sm-2"><input id="id_standard_capacity" maxlength="45" name="standard_capacity" type="text" value="{{form.standard_capacity.value}}" disabled /></div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-3">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2"><label for="id_Prime_percentage">Prime percentage:</label></label>

        <div class="col-sm-2"><input id="id_Prime_percentage" name="Prime_percentage" type="text" required /></div><!--actual input area-->
    </div>
	    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-3">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2">Standard Percentage</label>

        <div class="col-sm-2"><input type="text" id="std" onfocus="putValue()" /></div>
    </div>
        <div class="form-group">
            <div class="col-sm-offset-2-col-sm-3">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
	</form>
{% endblock %}

blog/templates/blog/post_list.html
{%extends 'blog/base.html' %}




{%block postlist%}










  <ul style="list-style-type:square;">
    <div >
 <div class="table-responsive">
  <table class="table">

      <thead>
    <tr>
    <th>LockerID</th>
    <th>Locker name</th>
      <th>City</th>
      <th>State</th>
      <th>PinCode</th>
        
        <th>Prime_Capacity</th>
        <th>Standard_Capacity</th>
        <th>Update</th>
        <th>Delete Record</th>
    </tr>
      </thead>
    <tbody>



      {% for post in posts %}
   <tr>

        <td> <a href="{% url 'post_detail' pk=post.pk %}">{{ post.locker_id }}</td><td>{{ post.locker_name }}</td><td>{{ post.city }}</td><td>{{ post.state }}</td><td>{{ post.pincode }}</td><td>{{ post.prime_capacity }}</td><td>{{ post.standard_capacity}}</td></a>

        <td><a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
        <td>
        <a  class="pull-right" href="{% url 'post_remove'  pk=post.pk %}">
                  <button type="button" class="btn btn-custom btn-margin">
                    <span class="glyphicon glyphicon-remove" ></span>

                                        Del

                    </button>
                </a>
 </td>

       </tr>
      {% endfor %}

        </tbody>
       </table>


 </div>
   </div>
    </ul>




{%endblock%}

blog/templates/blog/registration_form.html
{% extends 'blog/base.html' %}
{%block title%}Register{%endblock%}

{%block part%}
<div class="container-fluid">
<div class="row">
<div class="col-sm-12-col-md-7">
<div class ="panel panel-default">
<div class="panel-body">
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Add new account </h3>
{%if error_message%}
<p><strong>{{error_message}}</strong></p>
{%endif%}


<form method="POST" class="form-horizontal" role="form" action="" enctype="multipart/form-data">{% csrf_token %}
{%include 'blog/form-template.html'%}
<div class="form-group" >
<div class="col-sm-offset-2-col-sm-10">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


<button type="submit" class="btn btn-danger " >Submit</button>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</form>
{% endblock %}